### ISSUE TITLE
Post date bug

### ISSUE THREAD

**Issue by JEFworks** [itsrifat/rifyll#1]
There's a bug in `index.html`

```
              {% if page.lastmodified %}
                {{ page.lastmodified | date:'%A, %B %d, %Y'}}
              {% else %}
                {{ page.date | date:'%A, %B %d, %Y'}}
              {% endif %}
```

should be

```
              {% if post.lastmodified %}
                {{ post.lastmodified | date:'%A, %B %d, %Y'}}
              {% else %}
                {{ post.date | date:'%A, %B %d, %Y'}}
              {% endif %}
```

Otherwise, all current posts, as seen in your [demo](http://moinulhossain.me/rifyll/), show post dates of "Sunday, October 19, 2014" on the main page, which is the `index.html` page create date.

**Comment by itsrifat** [comment]
Fixed. I in fact removed the lastmodifieddate field not to complicate things. Its just `{{ post.date | date:'%A, %B %d, %Y'}}` now. Thanks!
